# Site configuration
# 1. Site Settings
  # 1.1. Site Logo,Favicons,Manifest and Icons
  # 1.2. Site Url, Links & Github Repo
  # 1.3. Site Colors & Typography

# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site setting
# 8. Resume 
# 9. Installed Gems
# 10. Files excluded from Jekyll builds

# 1. Site Settings
#################################################################################################

# 1.1. Site Logo,Favicons,Manifest and Icons
# -------------------------------------------
encoding: utf-8 # Make sure the encoding is right
lang: en # Set the site language
locale : en-IN
title: "Imswarnil" # Site name or title
description: "Personal website and portfolio of Swarnil Singhai, a Software Engineer at Twilio specializing in CRM Analytics, Salesforce, and web technologies. Based in Bangalore, India." # Site description
keywords: ["Swarnil Singhai", "Salesforce", "CRM Analytics", "Tableau CRM", "Einstein Analytics", "Apex", "LWC", "Software Engineer", "Twilio", "Bangalore", "Resume", "Portfolio"]
timezone: Asia/Kolkata # Timezone for blog posts and alike
short_name: "Swarnil" # The web application short name
logo: "/assets/logos/logo.svg" # Site logo
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# Author Configuration (imswarnil.yml or in _config.yml)
author:
  name: "Swarnil Singhai"
  short_name: "Swarnil"
  tagline: "Cinematic chaos meets code." # Feel free to tweak
  image: "/assets/imswarnil-profile.jpg"
  description: >
    I'm Swarnil — Software Engineer by day, Filmmaker by heart, and creative chaos incarnate all the time.
    I build with logic, I shoot with soul. Welcome to the multiverse of a data-loving storyteller.
  dob: "1994-05-23" # Date of Birth (YYYY-MM-DD)
  pronouns: "he/him"
  location: "Bangalore, India"
  nationality: "Indian"
  email: "contact@imswarnil.com"
  phone: "" # Optional
  website: "https://jekyll.imswarnil.com"
  resume_url: "/assets/Swarnil_Resume.pdf" # Adjust if hosted elsewhere
  github: "https://github.com/imswarnil"
  linkedin: "https://linkedin.com/in/imswarnil"
  youtube: "https://youtube.com/@imswarnil"
  instagram: "https://instagram.com/imswarnil"
  twitter: "https://twitter.com/imswarnil"

  # Setup and Preferences
  uses:
    operating_system: "macOS Ventura"
    computer: "MacBook Pro M2, 16GB RAM"
    editor: "VS Code + iTerm2"
    browser: "Arc Browser"
    terminal_theme: "Rosé Pine"
    phone: "iPhone 14 Pro"
    camera_gear:
      - "Sony ZV-E10"
      - "iPhone 14 Pro (Cinematic mode 😎)"
      - "GoPro Hero 11"
    mic: "Rode Wireless Go II"
    editing_software:
      - "Final Cut Pro"
      - "CapCut (mobile chaos edition)"
    design_tools:
      - "Figma"
      - "Canva Pro"
    productivity_stack:
      - "Notion"
      - "Obsidian"
      - "Cron Calendar"
      - "Raycast"
      - "CleanShot X"
    website_stack:
      - "Jekyll + Bulma CSS"
      - "Ghost CMS (legacy blog)"
      - "GitHub Pages"
    music_while_coding: "Lo-fi + Hans Zimmer + AR Rahman"
    backup_drive: "1TB SSD + Google Drive"
    favorite_fonts:
      - "JetBrains Mono"
      - "Satoshi"
    morning_routine: "Chai. Code. Chaos."

  # Skills
  skills:
    - name: "Tableau CRM (Einstein Analytics)"
      category: "CRM & Analytics"
      icon: "chart-bar"
    - name: "Salesforce Development"
      category: "CRM & Analytics"
      icon: "cloud"
    - name: "JavaScript (ES6+)"
      category: "Web Development"
      icon: "code"
    - name: "HTML / CSS / SCSS"
      category: "Web Development"
      icon: "file-html"
    - name: "Git & GitHub"
      category: "Dev Tools"
      icon: "github-logo"
    - name: "Jekyll"
      category: "Static Site Generators"
      icon: "stack-simple"
    - name: "Final Cut Pro"
      category: "Filmmaking"
      icon: "video-camera"
    - name: "Storytelling"
      category: "Creative"
      icon: "book-open"
    - name: "Public Speaking"
      category: "Soft Skills"
      icon: "microphone"

  # Use with Phosphor Icons (or Font Awesome alt)
  icon_library: "phosphor-icons"

  # Summary / Bio
  bio: >
    I'm not just a guy with a camera and a keyboard — I'm a man on a mission. From engineering dashboards to editing timelines, 
    I breathe narrative into numbers and soul into scripts. With 3 years in the Salesforce ecosystem, deep dives into data, 
    and a passion for storytelling, I create both products and perspectives. This site is my playground — part resume, part 
    portfolio, part personal logbook. Expect code, chaos, camera gear breakdowns, and stories straight from Bangalore's caffeinated streets.

  # Fun Stuff
  fun_facts:
    - "I once edited a video for 14 hours straight. No caffeine. Just vibes."
    - "I treat Notion like it's a second brain. And maybe it is."
    - "My aesthetic is somewhere between minimal monk and maximal meme lord."
    - "I believe even error messages can have personality."
    - "Half my YouTube videos start with: ‘So, here’s what happened…’"




social_media:
  - name: "twitter"
    icon : x-logo # (or fab fa-x-twitter)
    url: "https://twitter.com/imswarnil"
    cta: "Follow me on X"
  - name: "linkedin"
    icon : linkedin-logo # (or fab fa-linkedin)
    url: "https://linkedin.com/in/imswarnil" # General LinkedIn profile
    cta: "Connect on LinkedIn"
  - name: "github"
    icon: fab fa-github # Assuming Font Awesome
    url: "https://github.com/imswarnil"
    cta: "Follow on GitHub"
  - name: "youtube"
    icon: fab fa-youtube # Assuming Font Awesome
    url: "https://youtube.com/@imswarnil" # Or /imswarnil
    cta: "Subscribe on YouTube"
  - name: "instagram"
    icon: fab fa-instagram # Assuming Font Awesome
    url: "https://instagram.com/imswarnil"
    cta: "Follow on Instagram"

# --------------------------------------------
 # 1.2. Site Url, Links & Github Repo
 #----------------------------------------------------------------------------------------------
baseurl : '/'
url: 'https://imswarnil.github.io' # Site URL
permalink: /:title  # Permalink style
repo: "https://github.com/imswarnil/" # Your main GitHub profile
email: "contact@imswarnil.com" # General contact email for the site
description_separator: <!-- more -->

# 1.3. CSS, Site Colors & Typography
#------------------------------------------------------------------------------------------------
css_inline: false
sass:
  style: compressed
icon_style: duotone # Options: regular, thin, light, bold, fill, duotone  
theme_color : '#fff'
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Geist:wght@100&display=swap
    - https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap
    - https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap

# Robots And Indexing Settings
indexing: true
robots:
  bots:
    "*":
      disallow:
        - /404

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: true
  startings: [head, body]

# Service Worker Configuration
service_worker: true



google_analytics: "G-GGHMLZR4YQ"
adsense:
  enabled: true
  publisher:
    id: "ca-pub-1291242080282540"
    direct: "DIRECT"
    verification_id: "f08c47fec0942fa0"
  ads:
    - name: "Square Ad"
      width: 300
      height: 250
      ad_id: "1234567890"
      type: "display"
    - name: "Leaderboard Ad"
      width: 728
      height: 90
      ad_id: "0987654321"
      type: "display"
    - name: "Responsive Ad"
      width: "auto"
      height: "auto"
      ad_id: "5678901234"
      type: "auto"

include:
  - _pages

# 3. Gem settings
paginate: 3
paginate_path: "/archive/page:num/"


# 5. Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts, articles, and ideas on technology, Salesforce, and development."
    image: "https://picsum.photos/2560/600?image=866"
    permalink: /:categories/:title

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png"
      author: "Swarnil Singhai" 
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page

# 9. Site navigation (unchanged from your original for now, can be updated if needed)
fixed_navbar: true
navbar:
  - name: Home
    link: /
    icon: house
  - name: About # This could link to a page that uses resume data
    link: /about/
    icon: identification-card
    icon: "file-text" # e.g., ph-file-text or similar
  - name: Elements
    link: /elements/
    icon: puzzle-piece
  - name: Layouts
    link: /#
    icon: "layout"
    dropdown:
      - name: Post Layouts
        link: /#
        icon: article
      - name: Video Layout
        link: /videos/
        icon: play-circle
  - name: Categories
    link: /categories/
    icon: tag
  - name: Example Pages
    link: /#
    icon: "sparkle"
    dropdown:
      - name: Landing Page
        link: /landing/
        icon: rocket-launch
      - name: Sponsors Page
        link: /sponsors/
        icon: handshake
      - name: Image Gallery
        link: /gallery/
        icon: image
      - name: Products
        link: /products/
        icon: package
      - name: Recipe Page
        link: /example-recipe/
        image : "https://yt3.googleusercontent.com/bUPnDYABdzOveHZUSC-0745utTub-SQ76iuOjvYVUEeQrsA1fBMTgXbAsZ1SigmXd6BbtkqnwA=s900-c-k-c0x00ffffff-no-rj"
      - name: Showcase
        link: /showcase/
        icon: star

# Resume Section - Detailed Professional Information
#################################################################################################
resume:
  personal_details:
    full_name: "Swarnil Singhai"
    title: "Software Engineer (CRM Analytics)" # Your current primary title for resume
    location: "Bangalore, India"
    email: "contact@imswarnil.com" # Email for professional contact
    # phone: "+91 XXXXX XXXXX" # Optional: Add your phone number if you want it on the resume
    website: "https://jekyll.imswarnil.com" # Your portfolio website URL
    linkedin: "https://linkedin.com/in/imswarnil" # LinkedIn profile URL
    github: "https://github.com/imswarnil" # GitHub profile URL

  summary: > # Using `>` for multi-line string
    Results-driven Software Engineer with a strong background in Salesforce CRM Analytics (Tableau CRM/Einstein Analytics)
    and full-stack web development. Proven expertise in designing, developing, and deploying data visualization solutions
    and custom applications. Currently leveraging data to drive insights as a Tableau CRM Engineer at Twilio.
    Seeking to apply analytical and technical skills to solve complex challenges.

  work_experience:
    - company: "Twilio"
      role: "Tableau CRM Engineer"
      location: "Bangalore, India"
      start_date: "2021-12-23" # Please verify and use YYYY-MM-DD
      current: true
      description: # Use bullet points for responsibilities/achievements
        - "Develop and maintain Tableau CRM (Einstein Analytics) dashboards, datasets, and dataflows to provide actionable insights for internal stakeholders."
        - "Collaborate with business users to gather requirements and translate them into technical solutions."
        - "Optimize and troubleshoot existing analytics assets for performance and accuracy."
        - "Contribute to the overall data strategy and CRM analytics roadmap."
    - company: "Cognizant"
      role: "Project Associate (Tableau CRM)"
      location: "Bangalore, India"
      start_date: "2021-03-23" # Please verify
      end_date: "2021-12-22" # Please verify
      duration: "9 Months"
      description:
        - "Worked on client projects implementing Tableau CRM solutions, including data integration, dashboard development, and security setup."
        - "Delivered analytics solutions that helped clients understand key business metrics and trends."
        - "Gained hands-on experience with the full lifecycle of CRM Analytics projects."
    - company: "Accenture"
      role: "Software Engineer" # Last held role
      location: "Bangalore, India"
      start_date: "2018-03-23"
      end_date: "2021-03-22" # Please verify
      duration: "3 Years"
      description:
        - "Promoted from Associate Software Engineer to Software Engineer."
        - "Specialized in Salesforce Einstein Analytics, developing complex dataflows and interactive dashboards."
        - "Trained on various Salesforce technologies including Apex and Lightning Components."
        - "Contributed to multiple Salesforce implementation and enhancement projects."
    - company: "Kenscio"
      role: "Web Developer"
      location: "Bangalore, India" # Assuming
      start_date: "2018-01-15"
      end_date: "2018-04-14" # Approx 3 months, please verify
      duration: "3 Months"
      description:
        - "Developed and maintained client websites using HTML, CSS, JavaScript, and PHP in a fast-paced startup environment."
        - "Gained foundational experience in web development practices and version control."

  education:
    - degree: "Bachelor of Engineering in Computer Science" # PLEASE FILL: Your Degree
      institution: "Your University Name" # PLEASE FILL: Your University
      location: "City, State, India" # PLEASE FILL: University Location
      graduation_year: "2017" # PLEASE FILL: Your Graduation Year
      # details: # Optional, e.g., GPA, relevant coursework
      #   - "GPA: X.X/Y.Y"
      #   - "Relevant Coursework: Data Structures, Algorithms, Database Management, Web Technologies"

  skills:
    categories: # Grouping skills can be helpful for display
      - name: "CRM & Salesforce"
        items:
          - "Tableau CRM (Einstein Analytics)"
          - "Salesforce Platform"
          - "Apex"
          - "SOQL & SOSL"
          - "Lightning Web Components (LWC)"
          - "Salesforce Administration"
      - name: "Data & Analytics"
        items:
          - "Data Visualization"
          - "Data Modeling"
          - "ETL Processes"
          - "SQL"
      - name: "Web Technologies"
        items:
          - "JavaScript (ES6+)"
          - "HTML5"
          - "CSS3 / SCSS"
          - "REST APIs"
      - name: "Tools & Platforms"
        items:
          - "Git & GitHub"
          - "VS Code"
          - "JIRA / Agile Methodologies"
          - "Jekyll"
      - name: "Other"
        items:
          - "Problem Solving"
          - "Analytical Thinking"
          - "Communication"
    # You can also have a flat list if you prefer:
    # items:
    #   - name: "Salesforce Platform"
    #     icon: "fab fa-salesforce" # Example icon
    #   - name: "CRM Analytics (Tableau CRM)"
    #     icon: "fas fa-chart-line"
    #   - name: "Apex"
    #     icon: "fas fa-code"
    #   # ... and so on for all skills

  certifications: # PLEASE FILL: Add your certifications
    # - name: "Salesforce Certified Tableau CRM and Einstein Discovery Consultant"
    #   issuer: "Salesforce"
    #   date: "YYYY-MM" # Date obtained
    #   # verify_url: "URL_to_verification_if_any"
    # - name: "Salesforce Certified Platform Developer I"
    #   issuer: "Salesforce"
    #   date: "YYYY-MM"
    # - name: "Salesforce Certified Administrator"
    #   issuer: "Salesforce"
    #   date: "YYYY-MM"



# 8. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji


# 9. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .jekyll-cache
