# Site configuration
# 1. Site Settings
  # 1.1. Site Logo,Favicons,Manifest and Icons
  # 1.2. Site Url, Links & Github Repo
  # 1.3. Site Colors & Typography

# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site setting
# 8. Installed Gems
# 9. Files excluded from Jekyll builds

# 1. Site Settings
#################################################################################################

# 1.1. Site Logo,Favicons,Manifest and Icons
# -------------------------------------------
encoding: utf-8 # Make sure the encoding is right
lang: en # Set the site language
locale : en-IN
title: "Swarnil Singhai | Software Engineer" # Site name or title, also used in jekyll-seo-tag
description: "Personal website of Swarnil Singhai, a Software Engineer at Twilio specializing in CRM Analytics, Salesforce, and web technologies. Explore projects, articles, and insights." # Site description and default description, also used in seo
keywords: ["Swarnil Singhai", "Salesforce", "CRM Analytics", "Tableau CRM", "Einstein Analytics", "Apex", "LWC", "Software Engineer", "Twilio", "Bangalore", "Jekyll"]
timezone: Asia/Kolkata # Timezone for blog posts and alike
short_name: "Swarnil" # The web application short name, defaults to the site title
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'

# Author (Admin) Information
author:
  name: "Swarnil Singhai"
  short_name: "Swarnil" # Or "SS" if you prefer
  image : "/assets/logos/logo.svg" # Consider using a personal photo here
  description: "Passionate Software Engineer at Twilio with expertise in CRM Analytics (Tableau CRM/Einstein Analytics) and the Salesforce ecosystem. Based in Bangalore, India."
  location: "Bangalore, India"
  titles :
    - "Software Engineer at Twilio"
    - "CRM Analytics Specialist"
    - "Salesforce Developer"
    - "Content Creator"
  hobbies:
    - "Coding"
    - "Blogging / Content Creation"
    - "Exploring new technologies"
    - "Traveling"
  work_experience:
    - company: "Kenscio"
      role: "Web Developer"
      start_date: "2018-01-15"
      end_date: "2018-04-14" # Approx 3 months
      duration: "3 Months"
      details:
        - "Developed and maintained web applications in a startup environment."
        - "Gained experience with various web technologies."
    - company: "Accenture"
      role: "Software Engineer" # Last held role
      start_date: "2018-03-23"
      end_date: "2021-03-22" # Approx 3 years
      duration: "3 Years"
      details:
        - "Joined as an Associate Software Engineer."
        - "Trained extensively on the Salesforce platform (Apex, Lightning Components)."
        - "Specialized in Einstein Analytics (now CRM Analytics), developing dashboards and dataflows."
        - "Received a promotion to Software Engineer."
    - company: "Cognizant"
      role: "Project Associate"
      start_date: "2021-03-23" # Assuming immediate start after Accenture
      end_date: "2021-12-22" # Approx 9 months
      duration: "9 Months"
      details:
        - "Focused on Tableau CRM (formerly Einstein Analytics, now CRM Analytics) projects."
        - "Developed and implemented CRM Analytics solutions for clients."
    - company: "Twilio"
      role: "Tableau CRM Engineer" # Or "Software Engineer (CRM Analytics)"
      start_date: "2021-12-23" # Assuming immediate start after Cognizant
      current: true
      details:
        - "Currently working as a Tableau CRM Engineer, leveraging data to provide insights."
        - "Building and enhancing CRM Analytics solutions within the Twilio ecosystem."

social_media:
  - name: "twitter"
    icon : x-logo # (or fab fa-twitter if you are using Font Awesome v5/6, or fab fa-x-twitter for X logo)
    url: "https://twitter.com/imswarnil"
    cta: "Tweet"
  - name: "linkedin"
    icon : linkedin-logo # (or fab fa-linkedin)
    url: "https://linkedin.com/in/imswarnil" # Please verify this is your correct LinkedIn profile URL
    cta: "Connect on LinkedIn"
  - name: "github"
    icon: fab fa-github # Assuming Font Awesome for consistency
    url: "https://github.com/imswarnil"
    cta: "Follow on GitHub"
  - name: "youtube"
    icon: fab fa-youtube # Assuming Font Awesome
    url: "https://youtube.com/@imswarnil" # Or /imswarnil if it's a custom URL
    cta: "Subscribe on YouTube"
  - name: "instagram"
    icon: fab fa-instagram # Assuming Font Awesome
    url: "https://instagram.com/imswarnil"
    cta: "Follow on Instagram"
  # - name: "facebook" # Uncomment if you use it
  #   url: "https://facebook.com/imswarnil" # Update if needed
  #   cta: "Like on Facebook"

tech_stack: # Skills
  - name: "Salesforce Platform"
    icon: "fab fa-salesforce" # Font Awesome icon for Salesforce
  - name: "CRM Analytics (Tableau CRM)"
    icon: "fas fa-chart-line" # Example icon for analytics
  - name: "Einstein Analytics"
    icon: "fas fa-brain" # Example icon
  - name: "Apex"
    icon: "fas fa-code" # Generic code icon
  - name: "LWC (Lightning Web Components)"
    icon: "fas fa-bolt" # Lightning icon
  - name: "SOQL & SOSL"
    icon: "fas fa-database"
  - name: "JavaScript"
    icon: "fab fa-js-square"
  - name: "HTML5"
    icon: "fab fa-html5"
  - name: "CSS3"
    icon: "fab fa-css3-alt"
  - name: "Jekyll"
    icon: "fas fa-gem" # Example icon for Jekyll/Ruby gems
  - name: "VS Code"
    icon: "fas fa-code" # Already there, but good to keep

# --------------------------------------------
 # 1.2. Site Url, Links & Github Repo
 #----------------------------------------------------------------------------------------------
baseurl : ''
url: 'https://jekyll.imswarnil.com' # Site URL, also used in jekyll-seo-tag
permalink: /:title  # Permalink style /:categories/:title:output_ext
repo: "https://github.com/imswarnil/" # Your main GitHub profile, or a specific repo for the site if preferred
email: "contact@imswarnil.com"
description_separator: <!-- more --> # Marks end of description in posts

# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
#------------------------------------------------------------------------------------------------

# 1.3. CSS, Site Colors & Typography
#------------------------------------------------------------------------------------------------
css_inline: false # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
sass:
  style: compressed # Style compression
theme_color : '#fff'
# Typography
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Geist:wght@100&display=swap
    - https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap
    - https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap
# -------------------------------------------------
# 1.2. Robots And Indexing Settings
indexing: true
robots:
  bots:
    "*":
      disallow:
        - /404
# ========================================

# Service Worker Configuration
service_worker: true  # Master switch
manifest:
  id: "/?utm_source=pwa"
  orientation: "portrait"
  launch_handler:
    client_mode: "focus-existing"
  screenshots:
    - src: "/assets/screenshots/dummy-mobile-1.jpg"
      sizes: "540x720"
      type: "image/jpeg"
      form_factor: "narrow"
      label: "Dummy Screenshot 1 - Mobile View"
    - src: "/assets/screenshots/dummy-desktop-1.png"
      sizes: "1280x800"
      type: "image/png"
      form_factor: "wide"
      label: "Dummy Screenshot 2 - Desktop View"
  dir: "ltr"
  scope: "/"
  categories:
    - "news"
    - "social"
    - "lifestyle"
    - "technology" # Added category
  iarc_rating_id: "dummy_iarc_rating_123abc"
  related_applications:
    - platform: "play"
      url: "https://play.google.com/store/apps/details?id=com.example.app"
      id: "com.example.app"
  prefer_related_applications: false
  scope_extensions:
   - origin: "https://subdomain.example.com"
   - origin: "https://partner.example.com"

google_analytics: "G-GGHMLZR4YQ"
# google_analytics_anonymize_ip: ""
adsense:
  enabled: true
  publisher:
    id: "ca-pub-1291242080282540"
    direct: "DIRECT"
    verification_id: "f08c47fec0942fa0"
  ads:
    - name: "Square Ad"
      width: 300
      height: 250
      ad_id: "1234567890"
      type: "display"
    - name: "Leaderboard Ad"
      width: 728
      height: 90
      ad_id: "0987654321"
      type: "display"
    - name: "Responsive Ad"
      width: "auto"
      height: "auto"
      ad_id: "5678901234"
      type: "auto"


# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account

# Include these directories and files in the `_site` output
include:
  - _pages

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: /page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: imswarnil # jekyll-seo-tag > Owners twitter username
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]


# 5. Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts, articles, and ideas on technology, Salesforce, and development." # Updated description
    image: "https://picsum.photos/2560/600?image=866" # Consider a more personal or relevant banner
    permalink: /blog/:title

# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
      author: "Swarnil Singhai" # Default author for all content
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
      # author: "Swarnil Singhai" # Already set globally, but can be specific
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
      # author: "Swarnil Singhai" # Already set globally
  -
   scope:
      path: "_videos"
   values:
      layout: "video"
      author: "Swarnil" # Kept as "Swarnil" as per original specific request
  - scope:
      path: "_webseries"
      type: "webseries"
    values:
      layout: "webseries"
      author: "Swarnil Singhai" # Updated default author
      # Default images if none provided
      thumbnail: "https://m.media-amazon.com/images/M/MV5BMjg2NmM0MTEtYWY2Yy00NmFlLTllNTMtMjVkZjEwMGVlNzdjXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg"
      banner: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ0M0nOm5GHoz9vwFo093zwkz5zLFKPwx2e4Q&s"
      episode_thumb: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXHiiP7LIFPf0-8QIEEFYXRh4w_zoViLHVpKJI1V7avZe-SkxGXw6gMeH-jT8wywMfbBo&usqp=CAU"
  - scope:
      path: ""
      type: "projects" # Defaults specifically for the projects collection
    values:
      layout: project # We will create this layout soon
      author: "Swarnil" # Kept as "Swarnil" as per original specific request
      image: /assets/images/projects/placeholder.png # Default placeholder image
      category: ["Project"] # Default category if none specified


# 9. Site navigation
fixed_navbar: true # CRUCIAL: Make sure this is true
navbar:
  - name: Home
    link: /
    icon: house # ph-house
    dropdown:
      - name: Personal
        link: /personal/ # Added trailing slash
        icon: user # ph-user
  - name: About
    link: /about/
    icon: identification-card # (was fa-user) e.g., ph-identification-card
  - name: Elements
    link: /elements/
    icon: puzzle-piece # e.g., ph-puzzle-piece
  - name: Layouts
    link: /#
    icon: "layout" # e.g., ph-layout (was fa-app)
    dropdown:
      - name: Post Layouts
        link: /#
        icon: article # e.g., ph-article (was fa-pen)
      - name: Video Layout
        link: /videos/
        icon: play-circle # ph-play-circle
  - name: Categories
    link: /categories/
    icon: tag # ph-tag
  - name: Example Pages
    link: /#
    icon: "sparkle" # e.g., ph-sparkle
    dropdown:
      - name: Landing Page
        link: /landing/
        icon: rocket-launch # ph-rocket-launch
      - name: Sponsors Page
        link: /sponsors/
        icon: handshake # e.g., ph-handshake (was fa-hand-holding-heart)
      - name: Image Gallery
        link: /gallery/
        icon: image # ph-image or ph-images
      - name: Products
        link: /products/
        icon: package # e.g., ph-package (was fa-box-open)
      - name: Recipe Page
        link: /example-recipe/
        image : "https://yt3.googleusercontent.com/bUPnDYABdzOveHZUSC-0745utTub-SQ76iuOjvYVUEeQrsA1fBMTgXbAsZ1SigmXd6BbtkqnwA=s900-c-k-c0x00ffffff-no-rj"
        # icon: "cooking-pot" # e.g., ph-cooking-pot
      - name: Showcase
        link: /showcase/
        icon: star # ph-star
  - name: Search # Changed from link to name for consistency if it's a page
    link: /search/
    icon: magnifying-glass # ph-magnifying-glass


# 8. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 9. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .jekyll-cache