# Site configuration
# 1. Site Settings
  # 1.1. Site Logo,Favicons,Manifest and Icons
  # 1.2. Site Url, Links & Github Repo
  # 1.3. Site Colors & Typography

# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site setting 
# 8. Installed Gems
# 9. Files excluded from Jekyll builds

# 1. Site Settings 
#################################################################################################

# 1.1. Site Logo,Favicons,Manifest and Icons
# -------------------------------------------
encoding: utf-8 # Make sure the encoding is right
sidebar_nav : true 
lang: en # Set the site language
locale : en-IN 
title: "Im Jekyll Theme" # Site name or title, also used in jekyll-seo-tag
description: "An open-source Jekyll theme crafted using the Bulma CSS framework. This theme utilizes Bulma SCSS, making it incredibly easy to customize and adapt to your specific needs. With over 7 layouts and 10+ collections" # Site description and default description, also used in seo
keywords: ["Salesforce", "CRM", "Apex", "Lightning", "Trailhead", "Jekyll"]
timezone: Europe/London # Timezone for blog posts and alike
service_worker: false # Will turn off the service worker if set to false
short_name: "IMJKT" # The web application short name, defaults to the site title
logo: "/assets/logos/logo.svg" # Site logo, also used in jekyll-seo-tag
favicons: # Favicons are also used in the manifest file. Syntax is 'size: path'
  16: '/assets/logos/logo@16px.png'
  32: '/assets/logos/logo@32px.png'
  96: '/assets/logos/logo@96px.png'
  120: '/assets/logos/logo@120px.png'
  144: '/assets/logos/logo@144px.png'
  180: '/assets/logos/logo@180px.png'
  512: '/assets/logos/logo@512px.png'
  1024: '/assets/logos/logo@1024px.png'
# Author (Admin) Information
author:
  name: "John Doe"
  short_name: "JD"
  image : "/assets/logos/logo.svg"
  description: "A passionate developer and content creator who loves building open-source projects."
  titles :
    - "Software Engineer"
    - "Content Creator"
    - "Freelancer"
  hobbies:
    - "Coding"
    - "Blogging"
    - "Photography"
    - "Traveling"

social_media:
  - name: "twitter"
    url: "https://twitter.com/johndoe"
    cta: "Tweet"
  - name: "linkedin"
    url: "https://linkedin.com/in/johndoe"
    cta: "Connect on LinkedIn"
  - name: "github"
    url: "https://github.com/johndoe"
    cta: "Follow on GitHub"
  - name: "instagram"
    url: "https://instagram.com/johndoe"
    cta: "Follow on Instagram"
  - name: "facebook"
    url: "https://facebook.com/johndoe"
    cta: "Like on Facebook"
  - name: "website"
    url: "https://johndoe.com"
    cta: "Visit My Website"
  - name: "youtube"
    url: "https://youtube.com/johndoe"
    cta: "Subscribe on YouTube"


# --------------------------------------------
 # 1.2. Site Url, Links & Github Repo
 #----------------------------------------------------------------------------------------------
baseurl : ''
url: 'https://jekyll.imswarnil.com' # Site URL, also used in jekyll-seo-tag
permalink: /:title  # Permalink style /:categories/:title:output_ext
repo: "https://github.com/imswarnil/"
email: "contact@imswarnil.com"
description_separator: <!-- more --> # Marks end of description in posts
fixed_navbar : true
# date_format: "%-d %B %Y" # Blog post date formatting using placeholder formatting
#------------------------------------------------------------------------------------------------

# 1.3. CSS, Site Colors & Typography
#------------------------------------------------------------------------------------------------
css_inline: true # Will insert all styles into a single <style> block in the <head> element and remove the style <link> reference
sass:
  style: compressed # Style compression
theme_color : '#fff'
# Typography 
fonts:
  preconnect_urls:
    - https://fonts.gstatic.com
  font_urls:
    - https://fonts.googleapis.com/css2?family=Geist:wght@100&display=swap
    - https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap
    - https://fonts.googleapis.com/css2?family=Outfit:wght@100..900&display=swap 
# -------------------------------------------------
# 1.2. Robots And Indexing Settings 
indexing: true  # Global indexing control
robots:
  bots:
    "*":
      enabled: true
      disallow:
      - /404
      - /Search
      allow:
      - /

# ========================================

google_analytics: "G-GGHMLZR4YQ"
# google_analytics_anonymize_ip: ""
adsense:
  enabled: true
  publisher:
    id: "ca-pub-1291242080282540"
    direct: "DIRECT"
    verification_id: "f08c47fec0942fa0"
  ads:
    - name: "Square Ad"
      width: 300
      height: 250
      ad_id: "1234567890"
      type: "display"
    - name: "Leaderboard Ad"
      width: 728
      height: 90
      ad_id: "0987654321"
      type: "display"
    - name: "Responsive Ad"
      width: "auto"
      height: "auto"
      ad_id: "5678901234"
      type: "auto"


# disqus: "alembic-1" # Blog post comments, uncomment the option and set the site ID from your Disqus account

# 1.1. Site Logo,Favicons,Manifest and Icons

# Include these directories and files in the `_site` output
include:
  - _pages

# 3. Gem settings
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: DavidDarnes # jekyll-seo-tag > Owners twitter username
# markdown: CommonMark # Markdown parse settings, CommonMark performs slightly better an others in build time
# commonmark:
  # options: ["SMART", "FOOTNOTES"]
  # extensions: ["strikethrough", "autolink", "table"]


# 5. Collections
collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "My thoughts and ideas" # The post list page content
    feature_text: Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"
    permalink: /blog/:title
  training:
    output: true
    permalink: /:title/
  docs:
    output: true


# 6. Jekyll collections settings
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

# 9. Site navigation
navbar:
  - name: Home
    link: /
    icon: fa-home
    dropdown:
      - name: Personal
        link: /personal
        icon: fa-user
  - name: About
    link: /about/
    icon: fa-file
  - name: Elements
    link: /elements
  - name: Layouts
    link: /#
    dropdown:
      - name: Post Layout
        link: /blog
        icon: fa-pen
      - name: Video Layout
        link: /videos
        icon: fa-play
    icon: fa-app
  - name: Categories 
    link: /categories/
  - name: Example Pages
    link: /#
    dropdown:
      - name: Landing Page With Callouts
        link: /landing/
        icon: fa-rocket
      - name: Sponsors Page
        link: /sponsors/
        icon: fa-hand-holding-heart
      - name: Image Gallery
        link: /gallery/
        icon: fa-images
      - name: Products
        link: /products/
        icon: fa-box-open
      - name: Recipe Page
        link: /example-recipe/
        image : https://yt3.googleusercontent.com/bUPnDYABdzOveHZUSC-0745utTub-SQ76iuOjvYVUEeQrsA1fBMTgXbAsZ1SigmXd6BbtkqnwA=s900-c-k-c0x00ffffff-no-rj
      - name: Showcase
        link: /showcase/
        icon: fa-star
  - link: /search
    icon: fa-search


# 8. Installed Gems
plugins:
- jekyll-sitemap
- jekyll-paginate
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji

# 9. Files excluded from Jekyll builds
exclude:
- README.md
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- screenshot.png
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- .jekyll-cache