# frozen_string_literal: true
source "https://rubygems.org"
gem "jekyll"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jekyll-paginate"
gem "jekyll-redirect-from"
gem "jekyll-commonmark"
gem "jekyll-include-cache"
gem "jemoji"
gem "tzinfo-data"
gem "wdm"
